//! Generates `$OUT_DIR/idents.rs` from `../vectors/vectors.json`: one
//! `(identifier, bc_tags::TAG_X, bc_tags::TAG_NAME_X)` row per table entry.
//!
//! The TypeScript export name is the Rust identifier (`TAG_SEED` ↔
//! `bc_tags::TAG_SEED`); a legacy entry grouped under `LEGACY_TAGS`
//! (`SEED_V1`) is the flat `bc_tags::TAG_SEED_V1`. An identifier the crate
//! does not define fails to compile, so a constant that exists on one side
//! only cannot pass.
use std::{env, fs, path::Path};

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=../vectors/vectors.json");
    let json = fs::read_to_string("../vectors/vectors.json").expect("read ../vectors/vectors.json");
    let file: serde_json::Value = serde_json::from_str(&json).expect("parse ../vectors/vectors.json");
    let mut out = String::from(
        "/// Generated by build.rs from ../vectors/vectors.json: (identifier, value, name).\n\
         pub const IDENTS: &[(&str, u64, &str)] = &[\n",
    );
    for entry in file["table"].as_array().expect("table") {
        let c = entry["const"].as_str().expect("const");
        let ident = if c.starts_with("TAG_") { c.to_string() } else { format!("TAG_{c}") };
        let name_ident = format!("TAG_NAME_{}", &ident[4..]);
        out.push_str(&format!("    ({ident:?}, bc_tags::{ident}, bc_tags::{name_ident}),\n"));
    }
    out.push_str("];\n");
    let dest = Path::new(&env::var("OUT_DIR").expect("OUT_DIR")).join("idents.rs");
    fs::write(dest, out).expect("write idents.rs");
}
